from unittest import TestCase


class Test(TestCase):
    def test_problem1(self):
        self.fail()
